name: reminder
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  intl:
  hive_flutter:
  hive: ^2.2.3
  flutter_bloc: ^8.1.5
  equatable:
  get_it: ^7.7.0
  dartz:
  uuid:
  logger:
  flutter_local_notifications: ^17.1.2
  timezone: ^0.9.3
  flutter_timezone: ^1.0.8
  fluttertoast: ^8.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  hive_generator:
  build_runner:

flutter:

  uses-material-design: true

  assets:
    - assets/icons/

  fonts:
    - family: Roboto
      fonts:
#        - asset: assets/fonts/Roboto-Medium.ttf
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Thin.ttf
          weight: 100
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700



